### ISSUE TITLE
"Could not get contents underlying object!"

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#463]
Following errors logged after browsing the site and an activity stream did not load for a player.

INFO  Tue, 14 Feb 2017 11:17:41 -0500  application
$_GET = [ 'r' => 'space/space/stream' 'limit' => '10' 'from' => '' 'mode' => 'activity' 'sguid' => '4b5c0ccf-a747-494e-ae67-2e7e448a6cd6' ] $_SERVER = [ 'HTTP_HOST' => 'dev.humhub.m00.com.br' 'HTTP_CONNECTION' => 'keep-alive' 'HTTP_ACCEPT' => 'application/json, text/javascript, */*; q=0.01' 'HTTP_X_CSRF_TOKEN' => 'MlVOSFlqZG9mBAIeYCwTLEpnHit0KF0dfSd8Ah1bIAV/LwANHSEvWg==' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36' 'HTTP_REFERER' => 'http://dev.humhub.m00.com.br/index.php?r=missions%2Fspace%2Fmembers&sguid=4b5c0ccf-a747-494e-ae67-2e7e448a6cd6' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch' 'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.8,es;q=0.6' 'HTTP_COOKIE' => 'fs_uid=www.fullstory.com`21CH0`5629499534213120:5629499534213120; _csrf=d9867dd3751a1a4ba5598c33a4c7a1b79e86bce9393bb356380dd91ddedcde88a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22TQLV9FwCx2Pc-B9rOr2JD1DjMzNEDKK5%22%3B%7D; pm_space-members-panel=expanded; pm_user-spaces-panel=expanded; pm_profile-follower-panel=expanded; pm_profile-following-panel=expanded; language=9af3597d700b1e74cb505508460e6f1f74ffdf917785b0817ba7ed34f85c4562a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22en%22%3B%7D; pm_groups-statistics-panel=expanded; pm_new-people-panel=expanded; pm_user-statistics-panel=expanded; PHPSESSID=7b5u82u092tfuo919d5pk19k82; _gat=1; _ga=GA1.3.931910144.1486494935; mp_d2557637bad0bf1520733bad76dd4c3d_mixpanel=%7B%22distinct_id%22%3A%20%2215a383adfc4474-0b22d89a9ce2a1-1d3e6850-fa000-15a383adfc69c4%22%2C%22%24initial_referrer%22%3A%20%22http%3A%2F%2Fdev.humhub.m00.com.br%2Findex.php%3Fr%3Duser%252Fprofile%26uguid%3D65a129cd-e2ef-4261-ad1b-13ef0d53eb74%22%2C%22%24initial_referring_domain%22%3A%20%22dev.humhub.m00.com.br%22%7D; mp_mixpanel__c=0; _identity=59ae5cccac10c04bf5e1113b038afbe1d9553e85c93d4bef0e9d3699a3270fe1a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A51%3A%22%5B48%2C%2273ec8dfe-93f3-406d-a15f-b86151b8bbff%22%2C2592000%5D%22%3B%7D' 'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' 'SERVER_SIGNATURE' => '' 'SERVER_SOFTWARE' => 'Apache' 'SERVER_NAME' => 'dev.humhub.m00.com.br' 'SERVER_ADDR' => '45.55.160.126' 'SERVER_PORT' => '80' 'REMOTE_ADDR' => '24.217.116.34' 'DOCUMENT_ROOT' => '/srv/www/dev.humhub.m00.com.br' 'REQUEST_SCHEME' => 'http' 'CONTEXT_PREFIX' => '' 'CONTEXT_DOCUMENT_ROOT' => '/srv/www/dev.humhub.m00.com.br' 'SERVER_ADMIN' => 'webmaster@localhost' 'SCRIPT_FILENAME' => '/srv/www/dev.humhub.m00.com.br/index.php' 'REMOTE_PORT' => '53090' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' => 'r=space%2Fspace%2Fstream&limit=10&from=&mode=activity&sguid=4b5c0ccf-a747-494e-ae67-2e7e448a6cd6' 'REQUEST_URI' => '/index.php?r=space%2Fspace%2Fstream&limit=10&from=&mode=activity&sguid=4b5c0ccf-a747-494e-ae67-2e7e448a6cd6' 'SCRIPT_NAME' => '/index.php' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1487089061.513 'REQUEST_TIME' => 1487089061 ]

ERROR  Tue, 14 Feb 2017 11:17:41 -0500  yii\base\Exception
exception 'yii\base\Exception' with message 'Could not get contents underlying object!' in /srv/www/dev.humhub.m00.com.br/protected/humhub/modules/content/components/actions/Stream.php:249 Stack trace: #0 [internal function]: humhub\modules\content\components\actions\Stream->run() #1 /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array(Array, Array) #2 /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\Action->runWithParams(Array) #3 /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('stream', Array) #4 /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('space/space/str...', Array) #5 /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #6 /srv/www/dev.humhub.m00.com.br/index.php(25): yii\base\Application->run() #7 {main}

**Comment by Guihrmsfo** [comment]
Which player and which server?

**Comment by nathanverrill** [comment]
Dev
Logged in as admin, viewing the profile of the team Abriendo Caminos
http://dev.humhub.m00.com.br/index.php?r=space%2Fspace&sguid=4b5c0ccf-a747-494e-ae67-2e7e448a6cd6

**Comment by Guihrmsfo** [comment]
It's in activities widget, right?
It seems it's another humhub issue, maybe we should create a new panel on "Evoke Error's View" for activities, but I don't know its feasibility since activities are related to a lot of different entities.
@JayantGandhi @rjapur What are your thoughts?

**Comment by nathanverrill** [comment]
Or just don't show that panel on that page since if it never loads then it adds no value to the user. I also want to be able to monitor the error log on a regular basis without having to wade through the ones from the activity stream.

**Comment by nathanverrill** [comment]
That said, given our workload, I would rate this as a lower priority / non-critical item unless Jay feels otherwise.
