### ISSUE TITLE
hitting back button from page 1 of graphic novel causes "logged in, logout first!" error

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#519]
Info:
$_GET = [ 'r' => 'user/auth/create-account' 'token' => '58aef8767413a884686953' ] $_SERVER = [ 'HTTP_HOST' => 'soacha.evokenet.org' 'HTTP_CONNECTION' => 'keep-alive' 'HTTP_UPGRADE_INSECURE_REQUESTS' => '1' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36' 'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch' 'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.8,es;q=0.6' 'HTTP_COOKIE' => '_csrf=23bceb884bd6593bbb3bd040b2ede0973ca3882f104eef8139b780d38931857ca%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22iao-5-cB5g-TkZHpaGCZ0QGJpRRnHTsL%22%3B%7D; pm_space-members-panel=expanded; pm_user-spaces-panel=expanded; pm_groups-statistics-panel=expanded; pm_profile-follower-panel=expanded; pm_profile-following-panel=expanded; _gat=1; language=c21caa8de2b4a3c70b5d615fad65be36cc49d27d6c5d80a69a6dcdaf7b24779aa%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22es%22%3B%7D; PHPSESSID=n1e1v9qgomuagnrbu1m7cb80d6; _ga=GA1.2.1730528541.1487781436; pnctest=1' 'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' 'SERVER_SIGNATURE' => '<address>Apache/2.4.7 (Ubuntu) Server at soacha.evokenet.org Port 80</address> ' 'SERVER_SOFTWARE' => 'Apache/2.4.7 (Ubuntu)' 'SERVER_NAME' => 'soacha.evokenet.org' 'SERVER_ADDR' => '172.31.18.75' 'SERVER_PORT' => '80' 'REMOTE_ADDR' => '97.88.214.229' 'DOCUMENT_ROOT' => '/var/www/html/humhub' 'REQUEST_SCHEME' => 'http' 'CONTEXT_PREFIX' => '' 'CONTEXT_DOCUMENT_ROOT' => '/var/www/html/humhub' 'SERVER_ADMIN' => 'webmaster@localhost' 'SCRIPT_FILENAME' => '/var/www/html/humhub/index.php' 'REMOTE_PORT' => '54085' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' => 'r=user%2Fauth%2Fcreate-account&token=58aef8767413a884686953' 'REQUEST_URI' => '/index.php?r=user%2Fauth%2Fcreate-account&token=58aef8767413a884686953' 'SCRIPT_NAME' => '/index.php' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1487861948.41 'REQUEST_TIME' => 1487861948 ]

Error:
exception 'yii\web\HttpException' with message 'Your are already logged in! - Logout first!' in /home/ubuntu/humhub/protected/humhub/modules/user/controllers/AuthController.php:176 Stack trace: #0 [internal function]: humhub\modules\user\controllers\AuthController->actionCreateAccount() #1 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #2 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #3 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('create-account', Array) #4 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('user/auth/creat...', Array) #5 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #6 /home/ubuntu/humhub/index.php(25): yii\base\Application->run() #7 {main}

![image](https://cloud.githubusercontent.com/assets/273429/23264329/90e94aee-f9a6-11e6-8560-ce5d7eead0dc.png)

**Comment by Guihrmsfo** [comment]
This is the default error message when a user tries to re enter the login page by clicking on browser back button.
In my understanding there's nothing we could do.
@rjapur @JayantGandhi Any ideas?

**Comment by rjapur** [comment]
Yep, agreed. That's default behavior, not much we can do

**Comment by nathanverrill** [comment]
Per comment on a related issue... 

1. Needs to be localized
2. Can be addressed with text: "We couldn't find what you're looking for. Proceed to Base of Operations."

**Comment by Guihrmsfo** [comment]
Hey, @nathanverrill 
I'm sorry, I've been looking for the way I'd be able to do that, but I'm afraid it's not possible, it's a humhub default code, not a page. If it was a page, then we could overwrite it by creating page in themes with the same view name from humhub's

**Comment by nathanverrill** [comment]
@Guihrmsfo got it. Since the theme we're using currently is Soacha specific, what I would suggest is just replacing the text with helpful Spanish text (so then it will be in Spanish when viewing the site in English). Since it isn't a functional change and we'll never upgrade HumHub that should be straightforward so it's just text. Perhaps @JayantGandhi can provide text for us to use.

We're sorry, we couldn't find what you're looking for.
