### ISSUE TITLE
Infinite Scroll Not Working on Dashboard

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#572]
Go to dashboard as an admin, and try to scroll. The following error is logged.

exception 'yii\base\ErrorException' with message 'Undefined offset: 0' in /home/ubuntu/humhub/protected/modules/missions/widgets/views/mentor_review.php:38 Stack trace: #0 /home/ubuntu/humhub/protected/modules/missions/widgets/views/mentor_review.php(38): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/home/ubuntu/hu...', 38, Array) #1 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php(325): require('/home/ubuntu/hu...') #2 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/home/ubuntu/hu...', Array) #3 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/home/ubuntu/hu...', Array, NULL) #4 /home/ubuntu/humhub/protected/modules/missions/widgets/views/entry.php(103): yii\base\View->render('mentor_review', Array) #5 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php(325): require('/home/ubuntu/hu...') #6 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/home/ubuntu/hu...', Array) #7 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/home/ubuntu/hu...', Array, Object(humhub\modules\missions\widgets\WallEntry)) #8 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(191): yii\base\View->render('entry', Array, Object(humhub\modules\missions\widgets\WallEntry)) #9 /home/ubuntu/humhub/protected/modules/missions/widgets/WallEntry.php(46): yii\base\Widget->render('entry', Array) #10 /home/ubuntu/humhub/protected/humhub/modules/content/widgets/WallEntry.php(109): humhub\modules\missions\widgets\WallEntry->run() #11 /home/ubuntu/humhub/protected/humhub/modules/content/components/ContentActiveRecord.php(124): humhub\modules\content\widgets\WallEntry->renderWallEntry() #12 /home/ubuntu/humhub/protected/modules/missions/components/actions/FixedStream.php(261): humhub\modules\content\components\ContentActiveRecord->getWallOut() #13 [internal function]: humhub\modules\missions\components\actions\FixedStream->run() #14 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array(Array, Array) #15 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\Action->runWithParams(Array) #16 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('stream', Array) #17 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('missions/dashbo...', Array) #18 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #19 /home/ubuntu/humhub/index.php(25): yii\base\Application->run() #20 {main}

**Comment by nathanverrill** [comment]
apparently also the case for Carolina Cardozo Cantor from Green Hall group and Karen Lopez from Exodo team
