### ISSUE TITLE
Literacy branch "Review Evidence" does not work for Mentors

### ISSUE THREAD

**Issue by slacey** [EvokeNet/humhub#593]
Branch: Literacy
Instance: Limpopo pilot project, South Africa
Notice: Sept 09

Steps to reproduce: Log in to the instance (goo.gl/xv2jqc) as a Mentor (Mentor2/Mentor2) and review evidence. The screen shows any Agent's statistics, but the Evidence panel continually refreshes at the bottom and Evidence is not able to be reviewed.

The Error from the Log is as follows:
------
exception 'yii\base\ErrorException' with message 'Undefined offset: 0' in /var/www/html/themes/EvokeLiteracy/views/missions/widgets/mentor_review.php:38 Stack trace: #0 /var/www/html/themes/EvokeLiteracy/views/missions/widgets/mentor_review.php(38): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/var/www/html/t...', 38, Array) #1 /var/www/html/protected/vendor/yiisoft/yii2/base/View.php(325): require('/var/www/html/t...') #2 /var/www/html/protected/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/var/www/html/t...', Array) #3 /var/www/html/protected/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/var/www/html/t...', Array, NULL) #4 /var/www/html/themes/EvokeLiteracy/views/missions/widgets/entry.php(196): yii\base\View->render('mentor_review', Array) #5 /var/www/html/protected/vendor/yiisoft/yii2/base/View.php(325): require('/var/www/html/t...') #6 /var/www/html/protected/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/var/www/html/t...', Array) #7 /var/www/html/protected/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/var/www/html/p...', Array, Object(humhub\modules\missions\widgets\WallEntry)) #8 /var/www/html/protected/vendor/yiisoft/yii2/base/Widget.php(191): yii\base\View->render('entry', Array, Object(humhub\modules\missions\widgets\WallEntry)) #9 /var/www/html/protected/modules/missions/widgets/WallEntry.php(46): yii\base\Widget->render('entry', Array) #10 /var/www/html/protected/humhub/modules/content/widgets/WallEntry.php(109): humhub\modules\missions\widgets\WallEntry->run() #11 /var/www/html/protected/humhub/modules/content/components/ContentActiveRecord.php(124): humhub\modules\content\widgets\WallEntry->renderWallEntry() #12 /var/www/html/protected/modules/missions/components/actions/FixedStream.php(261): humhub\modules\content\components\ContentActiveRecord->getWallOut() #13 [internal function]: humhub\modules\missions\components\actions\FixedStream->run() #14 /var/www/html/protected/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array(Array, Array) #15 /var/www/html/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\Action->runWithParams(Array) #16 /var/www/html/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('stream', Array) #17 /var/www/html/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('missions/dashbo...', Array) #18 /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #19 /var/www/html/index.php(25): yii\base\Application->run() #20 {main}
---------------------------
### END ###

**Comment by slacey** [comment]
This issue can be considered CLOSED, as it has been found that Mission Activities without any Primary or Secondary Powers are what causes the index error. Therefore, all Mission Activities need to have Primary and Secondary Powers added to them, prior, and this effort is part of the EVOKE Facilitator/Admin and not a dev issue at this point.
